fix data-integrity: timestamp convert to datetime scenario
github/gh-ost pull request #969
Opened 2021-05-08 05:39 UTC by cenkore

related:  #161 #247 #269 ..

This PR is to fix the data integrity problem in timestamp conversion datetime scenarios.

**Env**

Variable_name  |  Value
:------------  |  ------------
system_time_zone  |  CST
time_zone 	|  +08:00

**Reason**
The timestamp time_zone parsed from binlog is CST +08:00, go-sql-driver will convert it to UTC +00:00 by default, and finally when applying to the database, even though add session query `set @@session.time_zone='+00:00'`, but because the column type has been changed to datetime, the time zone did not do conversion again, so the time zone was actually only converted by half, causing the data written to _xx_gho is 8 hours smaller.

**Solution**
In this case, change the time zone from +00:00 to the local system time zone, which is the opposite of datetime convert to timestamp.

Thank you !

2022-01-04 14:14 UTC, dm-2 commented
Fixed merge conflict for testing

2022-07-06 14:59 UTC, dm-2 approved these changes

2022-07-06 22:24 UTC, timvaillancourt approved these changes

2022-07-06 22:29 UTC, timvaillancourt commented
@cenkore / @dm-2 / @rashiq: as this converts data I'd like to be very sure it works now and in the future

Are there any tests that we can add to the `localtests/` dir that would:
1. Confirm `master` currently has a problem (test fails before changes in this PR)
2. Confirm the logic in this PR resolves the problem?
🤔

2022-07-06 22:29 UTC, timvaillancourt requested changes
@cenkore see my previous comment 🙏

2022-07-15 06:54 UTC, cenkore commented
> @cenkore see my previous comment 🙏
@timvaillancourt  Sorry for taking a long time to reply you.   PTAL.

2025-03-23 19:00 UTC, meiji163 commented
Is this still an issue? `localtests/tz-ts-datetime` test passes on the master branch. Also see https://github.com/github/gh-ost/pull/1322

2025-03-23 19:00 UTC, meiji163 commented
@cenkore Is this still an issue? `localtests/tz-ts-datetime` test passes on the master branch. Also see https://github.com/github/gh-ost/pull/1322

2025-04-29 07:01 UTC, cenkore commented
> @cenkore Is this still an issue? `localtests/tz-ts-datetime` test passes on the master branch. Also see #1322

It looks good. By the way, is this [restriction](https://github.com/github/gh-ost/blob/master/go/logic/inspect.go#L208) still necessary?

2025-05-16 16:17 UTC, closed without merging